//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHTP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeliveryPaysheet
    {
        [Display(Name = "Delivery Paysheet")]
        public int DeliveryPaysheetId { get; set; }
        [Display(Name = "Delivery")]
        public Nullable<int> DeliveryID { get; set; }
        [Display(Name = "Customer")]
        public Nullable<int> CustomerID { get; set; }
        [Display(Name = "Driver")]
        public Nullable<int> DriverID { get; set; }
        [Display(Name = "Order Date")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Display(Name = "Shipped Date")]
        public Nullable<System.DateTime> ShippedDate { get; set; }
        [Display(Name = "Waiting ")]
        public Nullable<int> WaitingID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Waiting Waiting { get; set; }
        public virtual Delivery Delivery { get; set; }
    }
}
