//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHTP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Deliveries = new HashSet<Delivery>();
        }

        [Display(Name = "Order Number")]
        public int OrdersId { get; set; }
        [Display(Name = "Customer")]
        public Nullable<short> CustomerID { get; set; }
        [Display(Name = " Driver")]
        public Nullable<short> DriverID { get; set; }
        [Display(Name = "Order Date")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Display(Name = "Shipped Date")]
        public Nullable<System.DateTime> ShippedDate { get; set; }
        [Display(Name = "Licenses")]
        public Nullable<int> TruckLicNum { get; set; }

        public Nullable<decimal> Freight { get; set; }
        [Display(Name = "Destination")]
        public Nullable<int> DestinationID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
